### ISSUE TITLE
Change to party affiliations from Lampi

### ISSUE THREAD

**Issue by lmullen** [mapping-elections/elections-data#35]
- [x] Matthew Lyon was a Republican in this [VT 1793] and other elections when he was a candidate. 
- [ ] Israel Smith [Vermont], was at least for a while supported by the Federalists as he was considered much more moderate than Lyon.

**Comment by lmullen** [comment]
Below are some political affiliations for Virginia 1789 – 1790.
 
- [x] District # 1           Alexander White [F]
- [x] District # 2           John Brown [F] in both. His opponent in 1790 was James M. Marshall [F]. Kentucky District.
- [x] District # 3           Andrew Moore [F] in both. His opponent in 1789  was George Hancock, who would later be elected as a Federalist.
- [x] District # 4           Richard B. Lee [F]in both. His opponent in 1789 was John Pope [AF] and in 1790 is was Arthur Lee [AF]
- [x] District # 5           James Madison [F] vs James Monroe [AF], there was a rematch in 1790, although Madison made have actually been unopposed in 1790.
- [x] District # 6           Isaac Coles [AF] in  1789, and Abraham B. Venable [AF] in 1790. 
- [x] District # 7           John Page [F] in both, one of his opponents in 1789 was Spencer Roane a [AF]
- [x] District # 8           Josiah Parker [AF] in both. In 1789 both his opponents were Federalists; Thomas Matthews and Isaac Avery, and Avery  again in 1790. Josiah Parker later moves into the Federalist ranks.
- [x] District # 9           Theodoric Bland [AF] in 1789; William B. Giles [AF] in 1790, his opponent Thomas Edmonds was a Federalist.               
- [x] District #10          Samuel Griffin [F] in both. In 1789 one of his opponents was Benjamin Harrison a [AF]

**Comment by lmullen** [comment]
Virginia 1793 – 1797
 
Between the elections of September 1790 and those of March 18, 1793, the was a Congressional reapportionment and Virginia gained nine seats. There were also some contentious political issues, which caused some of those elected in 1789/1790 to switch political allegiance. By 1793 the term Republican was becoming common, and is being used below.
 
1793

- [ ] District # 1           Robert Rutherford [R/F] was a former Federalist, who was encouraged to run, and received some Federalist support. The main aim was to defeat Alexander White, the incumbent Federalist congressmen.
- [ ] District # 2           Andrew Moore [R], one of those individual who switch from Federalist to Republican.
- [ ] District # 3           Joseph Neville [F] - Francis Preston was not a candidate in this district, but is in District # 4.
- [ ] District # 4           Francis Preston [R], his opponent Abraham Trigg was a [R]. This is a change in politics for Francis Preston from what you have.
- [ ] District # 5           George Hancock [F] - Both Charles Clay and Calohill Minnis in 1793 were [R]
- [ ] District # 6           Isaac Coles [R] 
- [ ] Districts # 7, 8, & 9, All successful candidates were Republicans and most had only scattered opposition.
- [ ] District #10          Carter B. Harrison [R], politics of his opponent are not known. This was a new district, so he may have been a Federalist, or a Republican.
- [ ] District #11          Josiah Parker [R] his opponent John Nevison was a Federalist.
- [ ] District #12          John Page [R], one of those individuals who switch from Federalist to Republican.
- [ ] District #13          Samuel Griffin[F]
- [ ] District #14          Francis Walker [R]
- [ ] District #15          James Madison [R]. Madison had by this election moved into the Republican party.
- [ ] District #16          Anthony New [R]. John Roane one if his opponents was a [R], and Francis Corbin a [F].
- [ ] District #17          Richard B. Lee [F]
- [ ] District #18          John Nicholas [R], his opponent William Pickett was a [F]
- [ ] District #19          John Heath [R], one of his opponents, Walter Jones was a [R], the other Francis L. Lee a [F].
 
1795
- [ ] District # 1           Robert Rutherford [R], now firmly in the Republican ranks, his opponent Daniel Morgan was a [F]
- [ ] District # 2           Andrew Moore [R]
- [ ] District # 3           George Jackson [R] his opponent being the incumbent Joseph Neville [F].
- [ ] District # 4           Francis Preston [R] his opponent was Arthur Campbell [F], he supported the Jay Treaty.
- [ ] District # 5           George Hancock [F]
- [ ] District # 6           Isaac Coles [R], his opponents were Matthew Clay [R] and Simon C. McMahon [F]
- [ ] District # 7           Abraham B. Venable [R], both of his opponents [Thomas Woodson and Joseph Wyatt] had offered limited opposition to him in 1793 and were probably Federalists.
- [ ] District # 8           Thomas Claiborne [R], his opponent Jesse Browne was a Federalist.
- [ ] District # 9, 10, 11 & 12   All were Republicans and except for Josiah Parker they were unopposed. Robert Cowper a Federalist ran against Josiah Parker.
- [ ] District #13          John Clopton [R], of his opponents Merriweather Jones was a [R]. Burwell Basset [F], but would later become a [R]. Miles Selden, Jr. had been a candidate in 1789, politics unknown.
- [ ] District #14, 15, & 16  All were Republicans and it appears unopposed.
- [ ] District #17          Richard Brent [R] defeating Richard B. Lee, the incumbent Federalist congressman.
- [ ] District # 18 & 19 Both were Republicans and apparently unopposed.
 
Note: Francis Preston and William B. Giles were both Republicans, this a change in politics from what you have listed.

**Comment by lmullen** [comment]
- [x] Connecticut – Virtually all the candidates mentioned or elected in Connecticut were Federalists. Because of the unique two tiered system of election congressmen, Republicans were almost always shut out and that party did not really begin to contest local or state elections until 1796 onward.

**Comment by lmullen** [comment]
- [x] New Hampshire – As with Connecticut, virtually all the candidates mentioned or elected were Federalists. Republican opposition began to start with a few running for Electors in 1796.

**Comment by lmullen** [comment]
South Carolina
1794
- [ ] District # 1 - William L. Smith and John Rutledge, Jr. were both Federalist.
- [ ] District # 5 – John Hunter was a Republican

**Comment by lmullen** [comment]
MA affiliations in a file

- [ ] [Massachusetts Political Affiliations 1790 -1796.docx](https://github.com/mapping-elections/elections-data/files/1528344/Massachusetts.Political.Affiliations.1790.-1796.docx)

**Comment by lmullen** [comment]
Georgia
1792
- [ ] Abraham Baldwin [AF/R] – He was re-elected, and based on the votes, received support from all parties.
- [ ] Thomas P. Carnes [F] – He was a State Representative from Franklin County, which he carried. He was also a candidate for US Senator in 1799 against Abraham Baldwin. The vote was surprisingly close [42 – 37].  He was also the Federalist candidate for Governor in the regular election of 1801 and a special one in 1802.  The votes in 1801 were [ 2 Reps. 41 & 7 – Carnes 21] and 1802 [John Milledge 48 – Thomas P. Carnes 22]. In both elections newspapers stated that Carnes was the federal candidate.
- [ ] George Mathews [F]
- [ ] John Milledge [R]
- [ ] Francis Willis [F] - He is the mystery man for this time period. Elected in 1790 when there were districts, he was defeated when they switched to At-Large. Apparently from Wilkes County he was popular in the up state counties. Almost all of his votes in 1792 came from those counties [Wilkes, Greene and Columbia]. In 1795 over half of his votes come from Wilkes County. In 1796 for Congress, Willis and Thomas P. Carnes [F], carry Wilkes and Greene while running close together in Jackson, Columbia, Elbert and Montgomery, all up state counties.
 
1795
- [ ] John Milledge [R]
- [ ] Abraham Baldwin [R]
- [ ] Thomas P. Carnes [F]
- [ ] Jacob B. Waldburger [F] - Not much is known about this individual, in 1795 he carried Greene, Hancock and was second in Burke. Over half of his votes come from these three counties. Greene in the early period was a Federalist county, which they carried for Congress and President in 1796.
- [ ] James Sims [R] – He was a State Representatives from Columbia County, which he carried, along with Warren and Burke, running second in Hancock. These four counties gave him over two thirds of his votes. Columbia County voted Republican.
- [ ] Francis Willis [F] – As mentioned above, of his 765 votes, 434 came from Wilkes, and it appears many of them were single votes, cast only for him.
 
What is very interesting about this election is that the two known Republicans [Milledge and Baldwin], ran poorly in several upstate counties [Burke, Wilkes, Greene, Franklin, Hancock and Warren], while Waldburger, Sims and Wills received little if any support in the down state counties.
 
1796
- [ ] Francis Willis [F] – Based on the votes from Carnes and Willis, which were close in many up state counties, Francis Willis was not supported so well in many down state counties, and is the reason there is such a separation in votes for these two  Federalist candidates.

**Comment by lmullen** [comment]
- [x] In DE 01 and DE 02, the Congressional Bio lists John Vining as a Federalist/Pro-Adminstration.

**Comment by lmullen** [comment]
- [x] In GA01, the CongBio lists the candidates as anti-Administration.
